apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: hemanth-deployment
  namespace: hemanth
spec:
  selector:
    matchLabels:
      app: hemanth
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: hemanth
    spec:
      containers:
      - name: hemanth
        image: 349948765351.dkr.ecr.ap-south-1.amazonaws.com/hemanth123:latest
        ports:
        - containerPort: 80
