apiVersion: v1
kind: Service
metadata:
  name: hemanth-service
  namespace: hemanth
spec:
  type: LoadBalancer
  selector:
    app: hs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
